[project]
name = "experiment"  
version = "0.1.0"  
dependencies = []  
requires-python = ">=3.11"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = false
